### ISSUE TITLE
Health Stat is still displaying incorrectly

### ISSUE THREAD

**Issue by EdwardMcCants** [Polatrite/TheTinyTheorycrafterGame#10]
Prior to 0.8.1, it seemed that the Health stat was simply adding the +increase% amount.  Now it seems to be simply adding 50*increase% amount.

I.e. previously 150 * 106% -> 156
Now 150 * 106% -> 153
I would expect that 150*106% -> 154.5

**Comment by Polatrite** [comment]
Fixed in 0.8.2
