### ISSUE TITLE
Inner Resonance is producing orbs based on cost/gen associated with an equipped skill

### ISSUE THREAD

**Issue by Ethret** [Polatrite/TheTinyTheorycrafterGame#11]
Example: Inner Resonance produces form if something GIVES or TAKES form. 

Inner Resonance doesn't consider actual skill type. (I put on inner resonance and basic attack and never produced any form orbs)

**Comment by Polatrite** [comment]
That's fine, Basic Attack will probably be one of the only skills to ever have no create or expend.
