### ISSUE TITLE
Theorycrafters Want For More Logues

### ISSUE THREAD

**Issue by KimberleySmith** [Polatrite/TheTinyTheorycrafterGame#14]
Adding in the Furthest screen to the info list was awesome, I thought it might be good to have a single place to put all the things that were being suggested to be included in the readouts, with a couple of my own wishes being more breakdowns of damage dealt (magic vs physical vs spiritual etc.), a more total breakdown of the time on current run (I know you want this game to have addition, but pls give us the simple things), a record of the last run's Quidity gain, possibly what level you got to, and just some general info on the previous run.

**Comment by Polatrite** [comment]
Fortunately I'm already keeping track of metrics for previous runs, so I plan to add the ability to "scroll back" through previous runs (and the full metrics panel worth of stats) in a future update.

Quiddity gain and quiddity use/sec and quiddity gained/sec for the run would be nice.

**Comment by Polatrite** [comment]
@KimberleySmith I would love to get your thoughts on this: https://github.com/Polatrite/TheTinyTheorycrafterGame/issues/20

**Comment by Polatrite** [comment]
Added a temporary combat log in v0.8.4, viewable in the browser control by hitting F12.
