### ISSUE TITLE
Poison Fang doesn't specify a duration or tick rate

### ISSUE THREAD

**Issue by wjomlex** [Polatrite/TheTinyTheorycrafterGame#15]
Poison Fang says it deals damage "over time" but doesn't say how long that DoT will last. Other abilities say things like "deals 40% of spell damage over 10s".

**Comment by Polatrite** [comment]
Poison's formula is too long for the ability descriptions, but I wrote an explanation on the wiki (which will get added to the game UI soon).

https://github.com/Polatrite/TheTinyTheorycrafterGame/wiki/Poison
