### ISSUE TITLE
Resource Heavy, memory leak?

### ISSUE THREAD

**Issue by Ethret** [Polatrite/TheTinyTheorycrafterGame#18]
Being able to run idle games in the background while doing other things is pretty important, and myself and others are noticing it's tough to do that.

**Comment by Polatrite** [comment]
Made a bunch of strides on this last night, hoping to have most of the biggest issues sorted out in the next patch.

**Comment by Polatrite** [comment]
Game has been running for about 4 hours - memory sitting roughly constant (only 40mb used) and no black screen bugs.

Maybe we're in better shape!

**Comment by Polatrite** [comment]
Fixed in 0.8.3... hopefully!
