### ISSUE TITLE
Slow and Steady Keystone causes players to lose Evasion score permanently

### ISSUE THREAD

**Issue by Polatrite** [Polatrite/TheTinyTheorycrafterGame#2]
Similar to the bug with Destroyer of Worlds, once a player takes Slow and Steady it will permanently set their Evasion score to 0, even after respec.

**Comment by KimberleySmith** [comment]
Looks like you might be nulling out the evasion "More" variable, rather than having it be set to 0, which causes it to read from the save file as an error maybe...

**Comment by Polatrite** [comment]
Fixed in 0.8.2
