### ISSUE TITLE
After playing for a while, whole computer's graphics reset, and TTTG stops rendering.

### ISSUE THREAD

**Issue by Ethret** [Polatrite/TheTinyTheorycrafterGame#5]
![image](https://user-images.githubusercontent.com/52941775/78511508-cb53f980-7762-11ea-81c7-5335895fa1c6.png)
I don't think it's a "me" problem, and wanted to bring it to light because I know others have seen it happen as well.

**Comment by Polatrite** [comment]
Fixed in 0.8.3... hopefully!
